{{-  if and .Values.ui.enabled .Values.auth.enabled .Values.auth.enabled -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: agentstack-oidc-providers
  labels:
    app.kubernetes.io/component: agentstack-ui
    app: agentstack-ui
stringData:
  providers.json: |
    {{ .Values.auth.providers | toJson }}
{{- end }}
